### ISSUE TITLE
I want to show the tabs conditionally but not working using showIf()

### ISSUE THREAD

**Issue by aasadFlic** [shuvroroy/nova-tabs#7] opened 2023-10-04 12:33 UTC
This is my resource Code 

<?php

namespace App\Nova;

use App\Models\Brand as ModelsBrand;
use App\Models\HomeScreenBanner;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\Boolean;
use Laravel\Nova\Fields\HasMany;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;
use Laravel\Nova\Fields\Image;
use Laravel\Nova\Fields\MorphMany;
use Laravel\Nova\Fields\Select;
use Outl1ne\NovaSortable\Traits\HasSortableRows;
use ShuvroRoy\NovaTabs\Tab;
use ShuvroRoy\NovaTabs\Tabs;
use ShuvroRoy\NovaTabs\Traits\HasActionsInTabs;
use ShuvroRoy\NovaTabs\Traits\HasTabs;

class Brand extends Resource
{
    use HasTabs, HasActionsInTabs;

    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\Brand::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'name';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id', 'name',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @return array
     */
    public function fields(NovaRequest $request)
    {
        $fields = [];
        $tabs = [];

        $fields[] = ID::make()->sortable()->onlyOnIndex();

        $fields[] =  Text::make('Name')
            ->rules('required', maxString())
            ->creationRules('unique:brands,name')
            ->updateRules('unique:brands,name,{{resourceId}}')->onlyOnIndex();

        $fields[] =  Text::make('Link')->onlyOnIndex();

        $fields[] = Image::make('Image')
            ->rules('required', 'image')
            ->rules('max:2048')
            ->help('Image size 2:1 such that i.e 200 X 100')->onlyOnIndex();

        $fields[] = Boolean::make('Active', 'is_enabled')
            ->trueValue(1)
            ->falseValue(0)
            ->rules('required')->onlyOnIndex();

        $fields[] = Text::make('Template Layout', function () {
            return view('nova.templateLayout', [
                'templateLayout' => $this->template_layout,
            ])->render();
        })->asHtml()->exceptOnForms();

        $fields[] =  Text::make('Name')
            ->rules('required', maxString())
            ->creationRules('unique:brands,name')
            ->updateRules('unique:brands,name,{{resourceId}}')->onlyOnForms();

        $fields[] = Select::make('Template Layout', 'template_layout')
            ->options([
                0 => 'No Layout',
                1 => 'Layout 1',
            ])
            ->displayUsingLabels()
            ->rules('required')
            ->withMeta(['value' => $this->template_layout ?? 0])->onlyOnForms();

        $fields[] =  Text::make('Link')->onlyOnForms();

        $fields[] = Image::make('Image')
            ->rules('required', 'image')
            ->rules('max:2048')
            ->help('Image size 2:1 such that i.e 200 X 100')->onlyOnForms();

        $fields[] = Boolean::make('Active', 'is_enabled')
            ->trueValue(1)
            ->falseValue(0)
            ->rules('required')->onlyOnForms();

        // $tabs = [];

        //  if (in_array($this->template_layout, [1])) {
        //     $tabs[] = Tab::make(__('homeScreenBanners'), [
        //         HasMany::make('Home Screen Banners', 'homeScreenBanners')
        //     ]);
        // }

        // $fields[] = Tabs::make('Brand', $tabs);

        // $showBanners = true;
        // $showFeatures = true;
        // $showAlwaysForYous = true;
        // $showLabels = true;  
        
        $showBanners = false;
        $showFeatures = false;
        $showAlwaysForYous = false;
        $showLabels = false;

        $brand = ModelsBrand::find((int)$request->resourceId);

        $templateLayoutVal = $brand?->template_layout;

        //template 1 settings
        if ($templateLayoutVal == 1) {

            $showBanners = true;
            $showFeatures = true;
            $showAlwaysForYous = true;
            $showLabels = true;
        }

        //dd($showBanners);

        $tabs[] = Tab::make(__('Banners'), [
            HasMany::make('Banners', 'banners')
        ])->showIf($showBanners);

        $tabs[] = Tab::make(__('Features'), [
            HasMany::make('Features', 'features')
        ])->showIf($showFeatures);

        $tabs[] = Tab::make(__('Always For Yous'), [
            HasMany::make('Always For Yous', 'alwaysForYous')
        ])->showIf($showAlwaysForYous);

        $tabs[] = Tab::make(__('Labels'), [
            HasMany::make('labels', 'labels')
        ])->showIf($showLabels);

        $tabs[] = Tab::make(__('Products'), [
            HasMany::make('Products'),
        ]);
        
        $fields[] = Tabs::make('Brands', $tabs);

        return $fields;
    }

    /**
     * Get the cards available for the request.
     *
     * @return array
     */
    public function cards(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @return array
     */
    public function filters(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @return array
     */
    public function lenses(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @return array
     */
    public function actions(NovaRequest $request)
    {
        return [];
    }
}

**Comment by shuvroroy** [comment] 2023-11-15 16:10
Closing this issue because of not properly explained how to reproduce this issue

**Closed as completed by shuvroroy** 2023-11-15 16:10 UTC
